version: '3.8'

services:
  db-test:
    image: postgres:15
    environment:
      - POSTGRES_DB=verificai_test
      - POSTGRES_USER=verificai_test
      - POSTGRES_PASSWORD=verificai_test123
    ports:
      - "5433:5432"
    networks:
      - verificai-test-network

  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - verificai-test-network

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://verificai_test:verificai_test123@db-test:5432/verificai_test
      - REDIS_URL=redis://redis-test:6379
      - ENVIRONMENT=test
    depends_on:
      - db-test
      - redis-test
    volumes:
      - ./backend:/app
      - ./test-results:/app/test-results
    networks:
      - verificai-test-network
    command: pytest tests/ --cov=app --cov-report=xml --cov-report=html -v

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - CI=true
      - REACT_APP_API_URL=http://backend-test:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - verificai-test-network
    command: npm run test:coverage

networks:
  verificai-test-network:
    driver: bridge