#!/usr/bin/env python3
"""
Setup script for Supabase integration
Creates table and initial configuration for remote deployment
"""

import os
import sys
from supabase import create_client

def setup_supabase():
    """
    Initialize Supabase with source_codes table
    Run this script once to set up the remote database
    """

    # Check if Supabase credentials are provided
    supabase_url = os.getenv('SUPABASE_URL')
    supabase_key = os.getenv('SUPABASE_KEY')

    if not supabase_url or not supabase_key:
        print("❌ Missing Supabase credentials!")
        print("Please set SUPABASE_URL and SUPABASE_KEY environment variables")
        print("Or update .streamlit/secrets.toml with your Supabase credentials")
        return False

    try:
        print("🔗 Connecting to Supabase...")
        supabase = create_client(supabase_url, supabase_key)

        # SQL to create the source_codes table
        create_table_sql = """
        CREATE TABLE IF NOT EXISTS source_codes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_id VARCHAR(255) UNIQUE NOT NULL,
            title VARCHAR(500) NOT NULL,
            description TEXT,
            content TEXT,
            file_name VARCHAR(500),
            file_extension VARCHAR(50),
            programming_language VARCHAR(100),
            line_count INTEGER,
            character_count INTEGER,
            size_bytes BIGINT,
            status VARCHAR(50) DEFAULT 'active',
            is_public BOOLEAN DEFAULT FALSE,
            is_processed BOOLEAN DEFAULT FALSE,
            processing_status VARCHAR(100) DEFAULT 'pending',
            code_metadata JSONB,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );

        -- Create indexes for performance
        CREATE INDEX IF NOT EXISTS idx_source_codes_code_id ON source_codes(code_id);
        CREATE INDEX IF NOT EXISTS idx_source_codes_status ON source_codes(status);
        CREATE INDEX IF NOT EXISTS idx_source_codes_created_at ON source_codes(created_at);
        CREATE INDEX IF NOT EXISTS idx_source_codes_programming_language ON source_codes(programming_language);

        -- Enable Row Level Security (RLS)
        ALTER TABLE source_codes ENABLE ROW LEVEL SECURITY;

        -- Create policy for public access (read only)
        CREATE POLICY "Public codes are viewable by everyone." ON source_codes
        FOR SELECT USING (is_public = true);

        -- Create policy for authenticated users
        CREATE POLICY "Users can insert their own codes." ON source_codes
        FOR INSERT WITH CHECK (true);

        -- Create policy for users to update their own codes
        CREATE POLICY "Users can update their own codes." ON source_codes
        FOR UPDATE USING (true);
        """

        print("📊 Creating source_codes table...")

        # Execute the SQL using Supabase RPC
        result = supabase.rpc('exec_sql', {'sql': create_table_sql}).execute()

        print("✅ Supabase setup completed successfully!")
        print("\n📋 Table created with the following structure:")
        print("  • id: Primary key (auto-increment)")
        print("  • code_id: Unique identifier")
        print("  • title: Code title")
        print("  • description: Code description")
        print("  • content: Source code content (TEXT field)")
        print("  • file_name: Original filename")
        print("  • file_extension: File extension")
        print("  • programming_language: Detected language")
        print("  • line_count, character_count, size_bytes: Statistics")
        print("  • status: 'active', 'deleted', etc.")
        print("  • created_at, updated_at: Timestamps")
        print("  • code_metadata: JSON metadata")
        print("  • RLS policies: Public read, user write/update")

        print(f"\n🌐 Supabase URL: {supabase_url}")
        print("🔑 Table is ready for remote deployment!")

        return True

    except Exception as e:
        print(f"❌ Error setting up Supabase: {str(e)}")

        # Fallback: provide manual SQL instructions
        print("\n📝 Manual setup required:")
        print("1. Go to your Supabase project dashboard")
        print("2. Open the SQL Editor")
        print("3. Run the following SQL:")

        manual_sql = """
        -- Create source_codes table
        CREATE TABLE IF NOT EXISTS source_codes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code_id VARCHAR(255) UNIQUE NOT NULL,
            title VARCHAR(500) NOT NULL,
            description TEXT,
            content TEXT,
            file_name VARCHAR(500),
            file_extension VARCHAR(50),
            programming_language VARCHAR(100),
            line_count INTEGER,
            character_count INTEGER,
            size_bytes BIGINT,
            status VARCHAR(50) DEFAULT 'active',
            is_public BOOLEAN DEFAULT FALSE,
            is_processed BOOLEAN DEFAULT FALSE,
            processing_status VARCHAR(100) DEFAULT 'pending',
            code_metadata JSONB,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );

        -- Create indexes
        CREATE INDEX IF NOT EXISTS idx_source_codes_code_id ON source_codes(code_id);
        CREATE INDEX IF NOT EXISTS idx_source_codes_status ON source_codes(status);
        CREATE INDEX IF NOT EXISTS idx_source_codes_created_at ON source_codes(created_at);
        CREATE INDEX IF NOT EXISTS idx_source_codes_programming_language ON source_codes(programming_language);

        -- Enable RLS
        ALTER TABLE source_codes ENABLE ROW LEVEL SECURITY;

        -- Create policies
        CREATE POLICY "Public codes are viewable by everyone." ON source_codes
        FOR SELECT USING (is_public = true);

        CREATE POLICY "Users can insert their own codes." ON source_codes
        FOR INSERT WITH CHECK (true);

        CREATE POLICY "Users can update their own codes." ON source_codes
        FOR UPDATE USING (true);
        """

        print(manual_sql)

        return False

if __name__ == "__main__":
    print("🚀 Supabase Setup for verificAI Code Manager")
    print("=" * 50)

    # Try to get credentials from secrets or environment
    try:
        import streamlit as st
        if hasattr(st, 'secrets'):
            supabase_url = st.secrets.get("SUPABASE_URL")
            supabase_key = st.secrets.get("SUPABASE_KEY")
            if supabase_url and supabase_key:
                os.environ['SUPABASE_URL'] = supabase_url
                os.environ['SUPABASE_KEY'] = supabase_key
    except:
        pass  # Streamlit not available, use environment variables

    success = setup_supabase()

    if success:
        print("\n🎉 Setup complete! Your app is ready for remote deployment.")
        print("\nNext steps:")
        print("1. Deploy to Streamlit Cloud")
        print("2. Add SUPABASE_URL and SUPABASE_KEY to app secrets")
        print("3. Set ENVIRONMENT='production' in app secrets")
        print("4. Test the deployment")
    else:
        print("\n❌ Setup failed. Please check the error messages above.")
        print("You may need to set up the table manually in Supabase dashboard.")