-- DDL para criar as tabelas no Supabase
-- Execute este SQL no editor SQL do seu projeto Supabase

-- Tabela para configurações de prompts
CREATE TABLE IF NOT EXISTS prompt_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_type VARCHAR(50) NOT NULL CHECK (prompt_type IN ('general', 'architectural', 'business')),
    name VARCHAR(255) NOT NULL DEFAULT '',
    content TEXT NOT NULL DEFAULT '',
    description TEXT,
    user_id BIGINT NOT NULL DEFAULT 1,
    is_active BOOLEAN DEFAULT true,
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by BIGINT,
    updated_by BIGINT
);

-- Tabela para códigos fontes
CREATE TABLE IF NOT EXISTS source_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_id VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(500) NOT NULL,
    description TEXT,
    content TEXT NOT NULL,
    file_name VARCHAR(500) NOT NULL,
    file_extension VARCHAR(50) NOT NULL,
    programming_language VARCHAR(100),
    line_count BIGINT DEFAULT 0,
    character_count BIGINT DEFAULT 0,
    size_bytes BIGINT DEFAULT 0,
    status VARCHAR(50) DEFAULT 'active' CHECK (status IN ('active', 'deleted')),
    is_public BOOLEAN DEFAULT false,
    is_processed BOOLEAN DEFAULT false,
    processing_status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela legada para prompts (mantida para compatibilidade)
CREATE TABLE IF NOT EXISTS prompts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    version INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Criar índices
CREATE INDEX IF NOT EXISTS idx_prompt_configurations_type ON prompt_configurations(prompt_type);
CREATE INDEX IF NOT EXISTS idx_prompt_configurations_active ON prompt_configurations(is_active);
CREATE INDEX IF NOT EXISTS idx_source_codes_status ON source_codes(status);
CREATE INDEX IF NOT EXISTS idx_source_codes_created_at ON source_codes(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_prompts_type ON prompts(type);

-- Inserir alguns prompts padrão se a tabela estiver vazia
INSERT INTO prompt_configurations (prompt_type, name, content, user_id, is_default)
SELECT
    'general',
    'Template Padrão - Critérios Gerais',
    'Analise o código fornecido considerando os seguintes critérios de qualidade:
1. **Princípios SOLID**: Verifique violações do Single Responsibility Principle e Dependency Inversion
2. **Acoplamento a Frameworks**: Detecte dependências excessivas de frameworks específicos
3. **Violação de Camadas**: Identifique lógica de negócio em camadas de interface
4. **Gerenciamento de Recursos**: Verifique liberação adequada de recursos externos
5. **Tratamento de Erros**: Analise blocos de exceção e tratamento de erros

Para cada critério, indique:
- Status: Conforme ou Não conforme
- Descrição detalhada dos problemas encontrados
- Recomendações específicas de correção
- Linhas de código afetadas',
    1,
    true
WHERE NOT EXISTS (SELECT 1 FROM prompt_configurations WHERE prompt_type = 'general');

INSERT INTO prompt_configurations (prompt_type, name, content, user_id, is_default)
SELECT
    'architectural',
    'Template Padrão - Conformidade Arquitetural',
    'Analise a conformidade arquitetural do código fornecido:
1. **Padrões de Projeto**: Verifique o uso adequado de padrões de projeto (Factory, Observer, Strategy, etc.)
2. **Arquitetura em Camadas**: Confirme a separação adequada entre camadas (UI, Service, Data)
3. **Injeção de Dependências**: Verifique a implementação correta de DI
4. **API Design**: Analise a consistência e boas práticas nas APIs
5. **Configuração e Segregação**: Verifique separação entre configuração e lógica de negócio

Avalie:
- Conformidade com padrões arquiteturais definidos
- Impacto das violações na manutenibilidade
- Sugestões de refatoração arquitetural
- Riscos técnicos identificados',
    1,
    true
WHERE NOT EXISTS (SELECT 1 FROM prompt_configurations WHERE prompt_type = 'architectural' AND is_default = true);

INSERT INTO prompt_configurations (prompt_type, name, content, user_id, is_default)
SELECT
    'business',
    'Template Padrão - Conformidade Negocial',
    'Analise a conformidade do código com regras de negócio:
1. **Validações de Negócio**: Verifique implementação de regras de negócio específicas
2. **Tratamento de Dados Sensíveis**: Confirme proteção adequada de dados críticos
3. **Auditoria e Logging**: Verifique registro de eventos de negócio importantes
4. **Cálculos e Fórmulas**: Valide precisão de cálculos de negócio
5. **Fluxos de Autorização**: Analise implementação de regras de acesso

Para cada regra de negócio:
- Status de conformidade
- Impacto no negócio em caso de violação
- Recomendações de correção
- Níveis de risco associados',
    1,
    true
WHERE NOT EXISTS (SELECT 1 FROM prompt_configurations WHERE prompt_type = 'business' AND is_default = true);

-- Habilitar Row Level Security (RLS) nas tabelas
ALTER TABLE prompt_configurations ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE prompts ENABLE ROW LEVEL SECURITY;

-- Políticas de RLS (permitir tudo por enquanto, pode ser refinado depois)
CREATE POLICY "Enable read access for all users" ON prompt_configurations FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON prompt_configurations FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON prompt_configurations FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON prompt_configurations FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON source_codes FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON source_codes FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON source_codes FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON source_codes FOR DELETE USING (true);

CREATE POLICY "Enable read access for all users" ON prompts FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON prompts FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON prompts FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON prompts FOR DELETE USING (true);