name: Deploy Preview

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Deploy to preview environment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/dist
        destination_dir: preview/${{ github.event.number }}

    - name: Comment PR with preview URL
      uses: actions/github-script@v7
      with:
        script: |
          const { issue: { number: pr_number }, repo: { owner, repo } } = context;
          const preview_url = `https://${owner}.github.io/${repo}/preview/${pr_number}/`;

          github.rest.issues.createComment({
            issue_number: pr_number,
            owner,
            repo,
            body: `🚀 **Preview Deployed Successfully!**

            **Preview URL:** ${preview_url}

            This preview will be automatically updated when new commits are pushed to this PR.

            ---
            *Deployed from commit: ${context.sha.substring(0, 7)}*`
          });